# Simulation settings for using moveit_sim_controllers
# moveit_sim_hw_interface:
#   joint_model_group: orion_arm
#   joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - J1
    - J2
    - J3
    - J4
    - J5
    - J6

  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: orion_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - J1
      - J2
      - J3
      - J4
      - J5
      - J6

orion_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - J1
    - J2
    - J3
    - J4
    - J5
    - J6
  pid_gains:
    J1:
      p: 1000
      d: 50
      i: 10
      i_clamp: 100
    J2:
      p: 5000
      d: 30
      i: 100
      i_clamp: 400
    J3:
      p: 5000
      d: 50
      i: 10
      i_clamp: 100
    J4:
      p: 200
      d: 20
      i: 10
      i_clamp: 100
    J5:
      p: 100
      d: 10
      i: 0.1
      i_clamp: 100
    J6:
      p: 10
      d: 1
      i: 0.1
      i_clamp: 100

  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0


    J1: {trajectory: 0.1, goal: 0.2}
    J2: {trajectory: 0.1, goal: 0.2}
    J3: {trajectory: 0.1, goal: 0.2}
    J4: {trajectory: 0.1, goal: 0.2}
    J5: {trajectory: 0.1, goal: 0.2}
    J6: {trajectory: 0.1, goal: 0.2}

  stop_trajectory_duration: 0.5
  state_publish_rate:  60
  action_monitor_rate: 30